### ISSUE TITLE
TypeError: Missing required arguments; Expected either ('messages' and 'model') or ('messages', 'model' and 'stream') arguments to be given

### ISSUE THREAD

**Issue by WilliamStone9846** [ayazaero/MobRobGPT#2]
Hello, I have a problem in using your code here, showing that the necessary parameters are not set, can you please provide a solution? Thank you very much.

**Comment by WilliamStone9846** [comment]
![WechatIMG1051](https://github.com/ayazaero/MobRobGPT/assets/97818100/1a69378d-953a-4321-979e-f2640fcfe394)

**Comment by ayazaero** [comment]
Hello, did you try the solutions mentioned in the link mentioned below? The error might be due to how the openai environment is setup. 

[https://community.openai.com/t/typeerror-missing-required-arguments-expected-either-messages-and-model-or-messages-model-and-stream-arguments-to-be-given/601646](https://community.openai.com/t/typeerror-missing-required-arguments-expected-either-messages-and-model-or-messages-model-and-stream-arguments-to-be-given/601646)

**Comment by WilliamStone9846** [comment]
> Hello, did you try the solutions mentioned in the link mentioned below? The error might be due to how the openai environment is setup.
> 
> [https://community.openai.com/t/typeerror-missing-required-arguments-expected-either-messages-and-model-or-messages-model-and-stream-arguments-to-be-given/601646](url)

After clicking on this link, it shows a blank page, was it removed by the author or some other problem?

**Comment by WilliamStone9846** [comment]
> > Hello, did you try the solutions mentioned in the link mentioned below? The error might be due to how the openai environment is setup.
> > [https://community.openai.com/t/typeerror-missing-required-arguments-expected-either-messages-and-model-or-messages-model-and-stream-arguments-to-be-given/601646](url)
> 
> After clicking on this link, it shows a blank page, was it removed by the author or some other problem?

<img width="1401" alt="image" src="https://github.com/ayazaero/MobRobGPT/assets/97818100/7cc7c015-35cb-4807-b78d-740681890cd4">

**Comment by ayazaero** [comment]
> > > Hello, did you try the solutions mentioned in the link mentioned below? The error might be due to how the openai environment is setup.
> > > [https://community.openai.com/t/typeerror-missing-required-arguments-expected-either-messages-and-model-or-messages-model-and-stream-arguments-to-be-given/601646](url)
> > 
> > 
> > After clicking on this link, it shows a blank page, was it removed by the author or some other problem?
> 
> <img alt="image" width="1401" src="https://private-user-images.githubusercontent.com/97818100/325444362-7cc7c015-35cb-4807-b78d-740681890cd4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMTAwMDUsIm5iZiI6MTcxNDAwOTcwNSwicGF0aCI6Ii85NzgxODEwMC8zMjU0NDQzNjItN2NjN2MwMTUtMzVjYi00ODA3LWI3OGQtNzQwNjgxODkwY2Q0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDAxNDgyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2ZDM0NzA0MzU0YjE0MDhlYmE4YmM3OTQzMzEzYmEzODc3NjI1ZWYxNjJhMjA2MWIzY2I4YWRmM2NiNzVjMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2YD9hvD6DPo0NqadI1Rmxw8gPfUkYmOQflgwW0NfQy0">

Try now. I updated the link

**Comment by WilliamStone9846** [comment]
> > > > Hello, did you try the solutions mentioned in the link mentioned below? The error might be due to how the openai environment is setup.
> > > > [https://community.openai.com/t/typeerror-missing-required-arguments-expected-either-messages-and-model-or-messages-model-and-stream-arguments-to-be-given/601646](url)
> > > 
> > > 
> > > After clicking on this link, it shows a blank page, was it removed by the author or some other problem?
> > 
> > 
> > <img alt="image" width="1401" src="https://private-user-images.githubusercontent.com/97818100/325444362-7cc7c015-35cb-4807-b78d-740681890cd4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMTAwMDUsIm5iZiI6MTcxNDAwOTcwNSwicGF0aCI6Ii85NzgxODEwMC8zMjU0NDQzNjItN2NjN2MwMTUtMzVjYi00ODA3LWI3OGQtNzQwNjgxODkwY2Q0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDAxNDgyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2ZDM0NzA0MzU0YjE0MDhlYmE4YmM3OTQzMzEzYmEzODc3NjI1ZWYxNjJhMjA2MWIzY2I4YWRmM2NiNzVjMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2YD9hvD6DPo0NqadI1Rmxw8gPfUkYmOQflgwW0NfQy0">
> 
> Try now. I updated the link

OK，thank you！ I will try again！If I success to solve this problem, I will tell you!

**Comment by WilliamStone9846** [comment]
I'm so sorry, I found a new problem like this"AttributeError: 'OpenAI' object has no attribute 'ChatCompletion'", what can I do for this? My openai=1.23.5
<img width="822" alt="image" src="https://github.com/ayazaero/MobRobGPT/assets/97818100/a6993a9b-95f2-498b-b7d5-b7df8dc72f8c">

**Comment by ayazaero** [comment]
mine is 1.6.0
Check this link.

[https://community.openai.com/t/attributeerror-module-openai-has-no-attribute-chatcompletion/81490](https://community.openai.com/t/attributeerror-module-openai-has-no-attribute-chatcompletion/81490)

**Comment by WilliamStone9846** [comment]
I retried it, my python version is 3.10.4 and my openai version is 1.23.5, and it ended up running as shown in the picture, so I'm not sure what the exact problem is with this one?
<img width="998" alt="image" src="https://github.com/ayazaero/MobRobGPT/assets/97818100/b1c1f926-5d22-4d89-aa1b-1ec1b3cec03e">
<img width="923" alt="image" src="https://github.com/ayazaero/MobRobGPT/assets/97818100/af59a650-7541-430c-8f3a-76f315f2334d">
This is really distressing for me.

**Comment by WilliamStone9846** [comment]
OK! I have solved this problem, thank you!

**Comment by ayazaero** [comment]
> OK! I have solved this problem, thank you!

Can you tell what was the issue and how did you solve it?

**Comment by WilliamStone9846** [comment]
> > OK! I have solved this problem, thank you!
> 
> Can you tell what was the issue and how did you solve it?

I changed the code on line 69 to "my_assistant = client.beta.assistants.create" and it ran successfully, and note the issue with your own version of openAI.

**Comment by WilliamStone9846** [comment]
I'm interested in the future work aspect you mentioned and I think we could have a lot to talk about. I'm currently working on path planning, and then I'm going to work on trajectory prediction, which will require me to approach LLM as you mentioned, and I have a few ideas to share and discuss with you. I think we can use chatGPT to predict the future trajectory of the robot in advance and take into account the surrounding dynamic obstacles or other robot movements to achieve more efficient obstacle avoidance. I have a paper here, which was posted on arXiv in advance, I can send it to you to take a look at "LC-LLM Explainable Lane-Change Intention and Trajectory Predictions with Large Language Models".

**Comment by ayazaero** [comment]
Send me a message on linkedin. [https://www.linkedin.com/in/ayazaero/](https://www.linkedin.com/in/ayazaero/)
